site_name: lume-services
site_url: https://slaclab.github.io/lume-services
repo_url: https://github.com/slaclab/lume-services
nav:
  - Overview: index.md
  - Notes: nodes.md
  - Configuration:
  - Services: 
    - Data: 
      - File Service: file_service.md
      - Model Service: model_service.md
      - Results Service: results_service.md
    - HPC: 
    - Modeling:
      - Remote Modeling Service: 
      - Local Modeling Service: 
      - Preprocessing:
      - Templating: 
    - Scheduling:
      - Scheduling Service: 
      - Prefect:
        - Prefect Scheduler: 
        - Results:
          - File Result:
          - DB Result: 
  - Developer:


plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            inherited_members: false
            filters:
              - "!^_"  # exlude all members starting with _
              - "^__init__$"  # but always include __init__ modules and methods
          rendering:
            show_source: true
