site_name: lume-services
site_url: https://jacquelinegarrahan.github.io/lume-services
repo_url: https://github.com/jacquelinegarrahan/lume-services
nav:
  - Overview: index.md
  - Notes: notes.md
  - Configuration: config.md
  - Services: 
    - Data: 
      - File Service: services/file_service.md
      - Model Registry: model_registry.md
      - Results DB: services/results_service.md
    - HPC: 
      - HPC Service: services/hpc_service.md
    - Modeling:
      - Modeling Service: services/modeling_service.md
      - Preprocessing: preprocessing.md
      - Packaging: model_packaging.md
    - Scheduling:
      - Scheduling Service: services/scheduling_service.md
      - Results: prefect_results.md
  - API:
    - Scheduling: 
      - scheduling service: api/scheduling/scheduling.md
      - backends: api/scheduling/backends.md
    - Data:
      - file service: api/data/file/file_service.md
      - file systems: api/data/file/filesystems.md

  #- Developer:
  #  - 
  #  - Structure:
  #  - Configuration Context:
  #- API:
  #  - ...


plugins:
  - search:
      separator: '[\s\-\.]'
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            inherited_members: false
            filters:
              - "!^_"  # exlude all members starting with _
              - "^__init__$"  # but always include __init__ modules and methods
          rendering:
            show_source: true
            show_root_toc_entry: false
            show_root_heading: true
            show_if_no_docstring: false
            show_signature_annotations: true
            separate_signature: true
            merge_init_into_class: true
            show_submodules: true
            heading_level: 2

theme:
  name: material
  features:
    - toc.integrate
    - toc.follow
    - navigation.top
    - navigation.tabs
