site_name: lume-services
site_url: https://jacquelinegarrahan.github.io/lume-services
repo_url: https://github.com/jacquelinegarrahan/lume-services
nav:
  - Overview: index.md
  - Notes: notes.md
  - Configuration: config.md
  - Model Packaging: model_packaging.md
  - Data: data.md
  - TODO: todo.md
  - Services:
    - File Service: services/file_service.md
    - Results DB Service: services/results_db_service.md
    - HPC Service: services/hpc_service.md
    - Modeling Service: services/modeling_service.md
    - Scheduling Service: services/scheduling_service.md
  - API:
    - Data:
      - Files:
        - Files: api/data/files.md
        - Serializers: api/data/files/serializers.md
      - results: api/data/results.md
    - Services:
      - Data:
        - Files:
          - File Service: api/services/data/files/file_service.md
          - Filesystems: api/services/data/files/filesystems.md
        - Results: api/services/data/results.md
        - Models: api/services/data/models.md
      - Scheduling: api/services/scheduling.md
  - Developer:
    - Setup:  developer/setup.md
    - Data:  developer/data.md
    - Testing:  developer/testing.md
    - Services:
      - File: developer/services/file.md
      - Scheduling: developer/services/scheduling.md

plugins:
  - search:
      separator: '[\s\-\.]'
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            inherited_members: true
            filters:
              - "!^_"  # exlude all members starting with _
              - "^__init__$"  # but always include __init__ modules and methods
          rendering:
            show_source: true
            show_root_toc_entry: false
            show_root_full_path: true
            show_root_members_full_path: true
            show_root_heading: true
            show_if_no_docstring: true
            show_signature_annotations: true
            separate_signature: true
            merge_init_into_class: true
            show_submodules: true
            heading_level: 2
            members_order: source
            show_category_heading: true

theme:
  name: material
  features:
    - toc.integrate
    - toc.follow
    - navigation.top
    - navigation.tabs

markdown_extensions:
  - pymdownx.tasklist
