site_name: lume-services
site_url: https://jacquelinegarrahan.github.io/lume-services
repo_url: https://github.com/jacquelinegarrahan/lume-services
nav:
  - Overview: index.md
  - Notes: notes.md
  - Configuration: config.md
  - Services: 
    - Data: 
      - File Service: file_service.md
      - Model Service: modeling_service.md
      - Results Service: results_service.md
    - HPC: 
      - HPC Service: hpc_service.md
    - Modeling:
      - Modeling Service: modeling_service.md
      - Preprocessing: preprocessing.md
      - Packaging: model_packaging.md
    - Scheduling:
      - Scheduling Service: scheduling_service.md
      - Results: prefect_results.md
  - API:
    - scheduling: 
      - scheduling service: api/scheduling.md
      - backends: 
        - backend: api/scheduling/backends.md
        - local: api/scheduling/backends/local.md
        - kubernetes: api/scheduling/backends/kubernetes.md
  #- Developer:
  #  - 
  #  - Structure:
  #  - Configuration Context:
  #- API:
  #  - ...


plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            inherited_members: false
            filters:
              - "!^_"  # exlude all members starting with _
              - "^__init__$"  # but always include __init__ modules and methods
          rendering:
            show_source: true

theme:
  name: material