site_name: lume-services
site_url: https://jacquelinegarrahan.github.io/lume-services
repo_url: https://github.com/jacquelinegarrahan/lume-services
nav:
  - Overview:
    - LUME-Services: index.md
  -   Notes: notes.md
  -   Configuration: config.md
  -   Model Packaging: model_packaging.md
  -   Workflows: workflows.md
  - Services:
    - File Service: services/file_service.md
    - Results DB Service: services/results_db_service.md
    - HPC Service: services/hpc_service.md
    - Modeling Service: services/modeling_service.md
    - Scheduling Service: services/scheduling_service.md
  - API:
    - Files:
      - File: api/files/files.md
      - Serializers: api/files/serializers.md
      - Utils: /api/files/utils.md
    - Results: api/results.md
    - Config: api/config.md
    - Errors: api/errors.md
    - Utils: api/utils.md
    - Flows: api/flows.md
    - Services:
      - Results:
        - Results Database Service: api/services/results/results.md
        - Database:  api/services/results/db.md
      - Files:
        - File Service: api/services/files/files.md
        - Filesystems: api/services/files/filesystems.md
      - Model:
          - Model Database Service: api/services/models/models.md
          - Database:  api/services/models/db.md
      - Scheduling:
          - Scheduling Service: api/services/scheduling/scheduling.md
          - Backends: api/services/scheduling/backends.md
  - Developer:
    - Setup:  developer/setup.md
    - Testing:  developer/testing.md
    - Documentation: developer/documentation.md
    - TODO: developer/todo.md
    - Cluster Architecture: developer/cluster.md
    - Services:
      - File: developer/services/file.md
      - Scheduling: developer/services/scheduling.md
      - Results: developer/services/results.md

plugins:
  - search:
      separator: '[\s\-\.]'
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            inherited_members: true
            filters:
              - "!^_"  # exlude all members starting with _
              - "^__init__$"  # but always include __init__ modules and methods
              - "!^logger"
          rendering:
            show_source: true
            show_root_toc_entry: false
            show_root_full_path: true
            show_root_heading: true
            show_if_no_docstring: true
            show_signature_annotations: true
            separate_signature: true
            merge_init_into_class: true
            show_submodules: true
            heading_level: 2
            members_order: source
            show_category_heading: true


theme:
  name: material
  features:
    - toc.integrate
    - toc.follow
    - navigation.top
    - navigation.tabs

markdown_extensions:
  - pymdownx.tasklist
#  - attr_list

extra_css:
  - stylesheets/extra.css
