name: Run tests

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    name: Test model execution
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,anaconda
          channel-priority: flexible
      - name: Create environment
        shell: bash -l {0}
        run: |
          conda config --set always_yes yes --set changeps1 no
          conda env create -f environment.yml
          conda activate {{ cookiecutter.project_slug }}
          conda install --file dev-requirements.txt
      - name: Run tests
        shell: bash -l {0}
        run: |
          conda activate {{ cookiecutter.project_slug }}
          pytest
