version: "3.7"
services:
  mysql:
    image: mysql/mysql-server:8.0
    ports:
        - ${LUME_MODEL_DB__PORT:-3306}:3306
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - service-net
   #   - default
    environment:
      MYSQL_ROOT_PASSWORD: ${LUME_MODEL_DB__PASSWORD:-password}
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_USER: ${LUME_MODEL_DB__USER:-root}

  # Mongodb
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${LUME_RESULTS_DB__USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${LUME_RESULTS_DB__PASSWORD:-password}
    ports:
      - ${LUME_RESULTS_DB__PORT:-27017}:27017
    networks:
      - service-net
    #  - default

  # PostgreSQL: the backing database which stores flow metadata
  postgres:
    image: "postgres:11"
    #ports:
    #  - "${LUME_PREFECT__POSTGRES__HOST_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${LUME_PREFECT__POSTGRES__USER:-prefect_user}
      POSTGRES_PASSWORD: ${LUME_PREFECT__POSTGRES__PASSWORD:-prefect_password}
      POSTGRES_DB: ${LUME_PREFECT__POSTGRES__DB:-prefect_db}

    volumes:
      - postgres:/var/lib/postgresql/data
  #    - ${LUME_PREFECT__POSTGRES__DATA_PATH:-/tmp/lume/postgresql}:/var/lib/postgresql/data
    networks:
      - prefect-server
    command:
      - "postgres"
      # explicitly set max connections
      - "-c"
      - "max_connections=150"
    healthcheck:
      test: pg_isready -q -d $${POSTGRES_DB:-prefect_db} -U $${POSTGRES_USER:-prefect_user} || exit 1
      interval: 10s
      timeout: 2s
      retries: 60
      start_period: 2s
    restart: always

  # Hasura: automatically generates a GraphQL schema from Postgres, provides most of the 'query' API
  hasura:
    image: "hasura/graphql-engine:v2.1.1"
    init: true
    #ports:
    #  - "${LUME_PREFECT__HASURA__HOST_PORT:-3000}:3000"
    command: "graphql-engine serve"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgresql://${LUME_PREFECT__POSTGRES__USER:-prefect_user}:${LUME_PREFECT__POSTGRES__PASSWORD:-prefect_password}@postgres:5432/${LUME_PREFECT__POSTGRES__DB:-prefect_db}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_SERVER_PORT: "3000"
      HASURA_GRAPHQL_QUERY_PLAN_CACHE_SIZE: 100
      HASURA_GRAPHQL_LOG_LEVEL: "warn"
      HASURA_GRAPHQL_V1_BOOLEAN_NULL_COLLAPSE: "true"
    networks:
      - prefect-server
    healthcheck:
      test: wget -O - http://hasura:$${HASURA_GRAPHQL_SERVER_PORT}/healthz &>/dev/null || exit 1
      interval: 10s
      timeout: 2s
      retries: 60
      start_period: 1s
    restart: always
    depends_on:
      - postgres

  # GraphQL: provides most of the 'mutation' GraphQL API
  graphql:
    image: "prefecthq/server:${LUME_PREFECT__SERVER__TAG:-latest}"
    #ports:
    #  - "${LUME_PREFECT__GRAPHQL__HOST_PORT:-4201}:4201"
    command: bash -c "prefect-server database upgrade -y && python src/prefect_server/services/graphql/server.py"
    environment:
      PREFECT_SERVER_DB_CMD: prefect-server database upgrade -y
      PREFECT_SERVER__DATABASE__CONNECTION_URL: postgresql://${LUME_PREFECT__POSTGRES__USER:-prefect_user}:${LUME_PREFECT__POSTGRES__PASSWORD:-prefect_password}@postgres:5432/${LUME_PREFECT__POSTGRES__DB:-prefect_db}
      PREFECT_SERVER__HASURA__ADMIN_SECRET: ${PREFECT_SERVER__HASURA__ADMIN_SECRET:-hasura-secret-admin-secret}
      PREFECT_SERVER__HASURA__HOST: hasura
      PREFECT_CORE_VERSION: ${PREFECT_CORE_VERSION:-"1.2.4"}
    networks:
      - prefect-server
    healthcheck:
      test: curl --fail --silent "http://graphql:4201/health" &> /dev/null || exit 1
      interval: 20s
      timeout: 2s
      retries: 60
      start_period: 1s
    restart: always
    depends_on:
      - hasura

  # Towel: runs a collection of simple services
  towel:
    image: "prefecthq/server:${LUME_PREFECT__SERVER__TAG:-latest}"
    command: "python src/prefect_server/services/towel/__main__.py"
    environment:
      PREFECT_SERVER__HASURA__ADMIN_SECRET: ${PREFECT_SERVER__HASURA__ADMIN_SECRET:-hasura-secret-admin-secret}
      PREFECT_SERVER__HASURA__HOST: hasura
    networks:
      - prefect-server
    restart: "always"
    depends_on:
      - graphql

  # Apollo: combines the hasura and graphql schemas into a unified schema, the primary API entrypoint
  apollo:
    image: "prefecthq/apollo:${LUME_PREFECT__SERVER__TAG:-latest}"
    ports:
      - "${LUME_PREFECT__SERVER__HOST_PORT:-4200}:4200"
    command: bash -c "./post-start.sh && npm run serve"
    environment:
      HASURA_API_URL: ${HASURA_API_URL:-http://hasura:3000/v1alpha1/graphql}
      PREFECT_API_URL: ${PREFECT_API_URL:-http://graphql:4201/graphql/}
      PREFECT_API_HEALTH_URL: ${PREFECT_API_HEALTH_URL:-http://graphql:4201/health}
      PREFECT_SERVER__TELEMETRY__ENABLED: ${PREFECT_SERVER__TELEMETRY__ENABLED:-true}
      GRAPHQL_SERVICE_HOST: http://graphql
      GRAPHQL_SERVICE_PORT: 4201
    networks:
      - prefect-server
      - service-net
    healthcheck:
      test: curl --fail --silent "http://apollo:4200/.well-known/apollo/server-health" &> /dev/null || exit 1
      interval: 10s
      timeout: 2s
      retries: 60
      start_period: 1s
    restart: always
    depends_on:
      - graphql
      - hasura

  # agent
  agent:
    image: prefecthq/prefect:1.2.3-python3.10
    command: >
      bash -c "prefect server create-tenant --name default --slug default &>/dev/null ;
      prefect agent docker start --label lume-services --agent-address http://localhost:5000/ --show-flow-logs --log-level DEBUG --network service-net"
    volumes:
        - type: bind
          source: ${LUME_SERVICES_ROOTDIR}/lume_services/docker/files/config.toml
          target: /root/.prefect/config.toml
          read_only: true
        - type: bind
          source: /var/run/docker.sock
          target: /var/run/docker.sock
          read_only: true
    environment:
      PREFECT__LOGGING__LEVEL: DEBUG
    ports:
      - ${LUME_PREFECT__AGENT__HOST_PORT:-5000}:5000
    depends_on:
      - apollo
      - mysql
      - mongodb
    restart: always
    networks:
      - service-net
    healthcheck:
      test: curl --fail --silent "http://agent:5000/api/health" &> /dev/null || exit 1
      interval: 10s
      timeout: 2s
      retries: 60
      start_period: 1s

  ui:
    profiles:
        - with_ui
    command: /intercept.sh
    depends_on:
      apollo:
        condition: service_started
    environment:
      PREFECT_SERVER__APOLLO_URL: http://localhost:4200/graphql
    healthcheck:
      interval: 30s
      retries: 3
      test: curl --fail --silent --head "http://ui:8080/" &> /dev/null || exit 1
      timeout: 5s
    image: prefecthq/ui:core-1.2.2
    networks:
      - prefect-server
    ports:
      - ${LUME_PREFECT__UI__HOST_PORT:-8080}:8080/tcp
    restart: always

volumes:
  postgres:

networks:
  prefect-server:
    name: prefect-server
  service-net:
    name: service-net
 #   driver: bridge
