name: Docs

on:
  push:
    branches:
      - main

jobs:
  build:
    if: ${{ github.repository == 'slaclab/lume-services' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
    name:  Build docs
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: conda-forge
          activate-environment: lume-services-dev
          environment-file: dev-environment.yml

      - name: Build package
        shell: bash -l {0}
        run: |
          pip install -e .

      - name: Build Schema Diagrams
        shell: bash -l {0}
        run: |
          python scripts/build_schema_diagrams.py generate-schema-docs \
            --uml_output_filename=docs/files/model_db_uml.png \
            --schema_output_filename=docs/files/model_db_schema.png

      - name: Build Docker Architecture
        shell: bash -l {0}
        run: |
          python scripts/diagrams/docker.py build-compose-docs --output_filename docs/files/docker_architecture.png

      - name: Build Env Vars
        shell: bash -l {0}
        run: |
          python scripts/build_configuration_table.py  build-configuration-table --output_filename docs/files/env_vars.md

      - name: Build and deploy
        shell: bash -l {0}
        run: |
          mkdocs build
          mkdocs gh-deploy --force
